### ISSUE TITLE
GatewayOS 4.2 - sx1302 reset pin

### ISSUE THREAD

**Issue by thinkl33t** [chirpstack/chirpstack-gateway-os#100]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-os/issues) of this repository and believe that this is not a duplicate.

## Summary

Please can we add an openwrt config variable for the `sx1302_reset_pin` on sx1302 for chirpstack-concentratord?

## What is the use-case?

I’m using an old RAK helium miner as a chirpstack gateway - its pretty much the same as the rak_2287 but needs `sx1302_reset_pin=25` setting in concentratord.conf to be detected.  Adding this config entry manually makes concentratord work fine with this board.

Currently i've been adding this to the config manuall but it gets overwritten every config change.

**Comment by brocaar** [comment]
From the CLI, you can (now) add a `sx1302_reset_pin` config option under the sx1302 configuration in `/etc/config/chirpstack-concentratord`. Then you need to restart using `/etc/init.d/chirpstack-concentratord`. This config change will be persisted :-)

See also:

https://github.com/chirpstack/chirpstack-openwrt-feed/blob/master/chirpstack/chirpstack-concentratord/files/chirpstack-concentratord.sh#L122

(There will be a new GW OS release today with some more improvements)
