### ISSUE TITLE
gRPC to REST API proxy for ChirpStack Gateway OS

### ISSUE THREAD

**Issue by scottmil** [chirpstack/chirpstack-gateway-os#102]
Can the gRPC to REST API proxy that is available for the Debian/Ubuntu ChirpStack 4 stack be made available for ChirpStack Gateway OS?

I have ChirpStack Gateway OS OpenWRT installed to control a STREGA LoRaWAN Smart Valve.  STREGA has created GUI widgets and a dashboard using TagoIO (https://tago.io/)  to allow the valve to be controlled from a smart phone app, but it appears REST POST commands are required for downlinks.

**Comment by brocaar** [comment]
I'm not planning to add this to the ChirpStack Gateway OS, but you should be able to run the ARMv7 binary yourself without issues on the ChirpStack Gateway OS: https://artifacts.chirpstack.io/downloads/chirpstack-rest-api/.
