### ISSUE TITLE
sx1301 concentratord.toml file path mistake

### ISSUE THREAD

**Issue by fernandobarreto** [chirpstack/chirpstack-gateway-os#108]
It's needed to change the file path of concentratord.toml for sx1301 script in /etc/init.d/chirpstack-concentratord to:

cat > /var/etc/chirpstack-concentratord/concentratord.toml <<- EOF

**Comment by marekpow** [comment]
Are you the root user?
Could you try to do this first:

sudo su

**Comment by fernandobarreto** [comment]
Yeah, I know that, thanks. The issue raised here is a contribution for a new future chirpstack gateway OS release, because the chirpstack-concentratord for sx1301 does not start with the original script due this error.
