### ISSUE TITLE
GPS CS OS return chaotic data

### ISSUE THREAD

**Issue by marekpow** [chirpstack/chirpstack-gateway-os#109]
- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-os/issues) of this repository and believe that this is not a duplicate.

## What happened?
GPS returns chaotic data. I used cat /dev/ttyAMA0 to catch data from GPS.
![image](https://github.com/chirpstack/chirpstack-gateway-os/assets/7034666/46a8193a-c4e9-4247-9c5d-c2328f338b74)

## What did you expect?
My gateway position should be displayed on the gateway bridge map.

## Steps to reproduce this issue

Steps:

1. Use RAK5146 on RPi 4

![image](https://github.com/chirpstack/chirpstack-gateway-os/assets/7034666/8a4167d5-4eff-40e8-b3cf-fa45a290588a)

## Could you share your log output?

```shell
The log doesn't show any errors about /dev/ttyAMA0
```

## Your Environment

| Component             | Version |
| ----------------------| ------- |
| ChirpStack Gateway OS | v4.3.0  |

**Comment by brocaar** [comment]
> GPS returns chaotic data. I used cat /dev/ttyAMA0 to catch data from GPS.

This data comes directly from the GNSS module (attached to the UART pins of the Raspberry Pi). There is nothing in the ChirpStack Gateway OS that influences the NMEA output. Most likely, the GNSS module wasn't able to acquire a GNSS lock yet.
