### ISSUE TITLE
IC880A change Reset Pin 

### ISSUE THREAD

**Issue by sdavid6338** [chirpstack/chirpstack-gateway-os#111]
Can you add the possibility to change the reset_pin number for an ic880a concentrator board (sx1301) ?

**Comment by ToSolveFaberM** [comment]
Hello, I would be impressed in this option also. Thanks

**Comment by brocaar** [comment]
The above commit will make it possible to add a `sx1301_reset_pin` config option to your `/etc/config/chirpstack-concentratord` config file. You would add it to this section: https://github.com/chirpstack/chirpstack-openwrt-feed/blob/master/chirpstack/chirpstack-concentratord-target-rpi/files/chirpstack-concentratord.config#L5
