### ISSUE TITLE
Wifi not reconnecting after AP/Router failure on PI Zero W

### ISSUE THREAD

**Issue by gbraux** [chirpstack/chirpstack-gateway-os#79]
Hello team,

If Wifi get disconnected (by the far end AP, or low signal), chirpstack OS is not trying to reconnect anymore even when the AP is back. The only way to get back wifi connectivity is to hard reboot the PI.

There should be some tweaks to make on Connman or WPA_Supplicant ...

Br,
G.

**Comment by brocaar** [comment]
I'm closing this issue as I'm not sure if it is still relevant after Yocto -> OpenWrt migration.
