### ISSUE TITLE
add Semtech SX1302 CoreCell CN490 to chirpstack-gateway-os

### ISSUE THREAD

**Issue by blockchain4trust** [chirpstack/chirpstack-gateway-os#84]
China occupies more than 50% of the LoRa market, and more and more developers are making gateways based on sx1302. It is strange that there is no CN490 option in ChirpStack-Gateway-OS.

For this, I have added the sx1302c490gw1_cn490.rs file [sx1302c490gw1_cn490.zip](https://github.com/brocaar/chirpstack-gateway-os/files/8211213/sx1302c490gw1_cn490.zip), hoping that the next version of ChirpStack-Gateway-OS
 will add the CN490 band. Let more Chinese users use ChirpStack, enrich the community, and exert greater influence.

**Comment by mx-cyber** [comment]
How do I add this file? Can you help me?

**Comment by brocaar** [comment]
Please make a pull-request here first: https://github.com/brocaar/chirpstack-concentratord/ to add support for this module in the Concentratord component.

**Comment by brocaar** [comment]
This was implemented :)
