### ISSUE TITLE
SX1303/RAK5146 support

### ISSUE THREAD

**Issue by jonasniesner** [chirpstack/chirpstack-gateway-os#90]
I am using chirpstack os with a RAK5146 (SPI+GPS EU868) and a raspberry pi. I am using the config for the rak_2287 and it mostly workes. The only thing not working at the moment is fine timestamp. Would it be possible to create a config for the RAK5146 and be able to get fine timestamps?

**Comment by brocaar** [comment]
Support for the RAK5146 has been added some time ago:
https://github.com/chirpstack/chirpstack-concentratord/blob/master/chirpstack-concentratord-sx1302/src/config/vendor/rak/rak5146.rs
