### ISSUE TITLE
US915 Support for LoRa concentrator shield option 13

### ISSUE THREAD

**Issue by IntegralWorks** [chirpstack/chirpstack-gateway-os#91]
If you go to https://wiki.seeedstudio.com/WM1302_module/ on the cover page is this model of WM1302: 
![image](https://user-images.githubusercontent.com/27093212/197269785-41d80695-c947-473c-bfca-7ac9633bf868.png)

There is currently no US915 band option in LoRa concentrator shield option 13 [when using version 4.0.0](https://artifacts.chirpstack.io/downloads/chirpstack-gateway-os/raspberrypi/raspberrypi4/4.0.0/):
![image](https://user-images.githubusercontent.com/27093212/197269614-fd580852-3b5e-41f0-8083-3e462539d393.png)

- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-os/issues) of this repository and believe that this is not a duplicate.

## What is the use-case?
A: For users of chirpstack-gateway-os that are trying to use the WM1302-SPI-US915-M model of the LoRaWAN® Gateway Module WM1302 product from Seeed Technology Co.,Ltd

## Implementation description
It appears that all the work needing to be done is plain text configuration.
## Can you implement this by yourself and make a pull request?
I need a maintainer to review my pull request [please].
- [x] Pull request: https://github.com/chirpstack/chirpstack-gateway-os/pull/92

**Comment by brocaar** [comment]
This has already been implemented.
