### ISSUE TITLE
Missing wireguard binaries

### ISSUE THREAD

**Issue by fernandobarreto** [chirpstack/chirpstack-gateway-os#93]
I was trying to test the Chirpstack 4.0.0 Gateway OS for RaspPi3, and I realized that the wireguard binaries (/usr/bin/wg and /usr/bin/wg-quick) are missing from Gateway OS base image.

**Comment by brocaar** [comment]
Thanks for reporting, I can reproduce the issue. This was caused by a syntax change in Yocto, will push a fix shortly.

**Comment by brocaar** [comment]
Fixed by the above commit.
