### ISSUE TITLE
NODE RED problem on version 4.0.1

### ISSUE THREAD

**Issue by stathisioannides** [chirpstack/chirpstack-gateway-os#95]
We were using NODE RED on version 4.0 with no problems.

We updated to version 4.0.1 using : chirpstack-gateway-os-full-update-raspberrypi4-20221114095641.swu
but after reboot of Pi4 was impossible to connect on NODE RED ( IP:1880 ) althought it was enabled.

We disabled and reenabled it through gateway-config,  after that we had a succesfull connection but the flows we had built where changed. We build them again and the system start working.

But after 2-3 message transfers connection with NODE RED server was lost again. We tried the disable-enable cycle of NODE RED but the problem persists.

**Comment by brocaar** [comment]
What are the minimum steps to reproduce this issue? Could you further explain what this means?

> But after 2-3 message transfers connection with NODE RED server was lost again. 

What does "message transfers" mean in this case?

**Comment by brocaar** [comment]
Thanks, I'm able to reproduce the issue. For some reason, NodeJS is throwing a "Bus error" and terminates.

```
12 Dec 12:23:22 - [info] Starting flows
12 Dec 12:23:22 - [info] Started flows
12 Dec 12:23:22 - [info] [mqtt-broker:localhost] Connected to broker: mqtt://localhost:1883
Bus error
```

I'll investigate this further.

**Comment by brocaar** [comment]
Quick update, I've tried various things:

* Updating Node-RED
* Updating node-red-contrib-chirpstack package
* Different ways of packaging the above packages
* Installing these packages by hand on the Pi

But this doesn't solve the issue. I'm now trying to update NodeJS to a later version (16.18.1) in the hope that this will resolve the issue :crossed_fingers: 

There have been several reports by other uses (non ChirpStack related), in which case it was either resolved by deleting the `node_packages` directory and `npm install ...` everything again or updating NodeJS.

**Comment by brocaar** [comment]
@stathisioannides the above commit fixes this issue.
