### ISSUE TITLE
Add support for Seeed reTerminal DM CM4 

### ISSUE THREAD

**Issue by trlafleur** [chirpstack/chirpstack-gateway-os#99]
- [x ] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-os/issues) of this repository and believe that this is not a duplicate.

## Summary

Seeed reTerminal DM needs display and other drivers to run, nice to have a build for this RPI4 variant

**Comment by brocaar** [comment]
> Seeed reTerminal DM needs display and other drivers to run

I'm closing this issue. I have no intentions in adding support for graphical output.
